DrinkAndGo/Models/User.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace DrinkAndGo.Models
{
    public class User
    {
        [Key]
        public int Id { get; set; }

        public string UserName { get; set; }

        public int Age { get; set; }

        [DataType(DataType.Password)]
        public string Password { get; set; }

        public string Role { get; set; }


        public List<Cart_Drink> Cart { get; set; } // will hold the connections between a user and a drink

        //public Dictionary<int, int> DrinkToCount { get; set; } // dict[drinkID] = drinkCount


        //public Cart Cart { get; set; }

        public User()
        {
            Cart = new List<Cart_Drink>();
            //DrinkToCount = new Dictionary<int, int>();
        }

    }
}

DrinkAndGo/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DrinkAndGo.Models;

namespace DrinkAndGo.Controllers
{
    public class OrdersController : Controller
    {
        private readonly DrinkAndGoContext _context;

        public OrdersController(DrinkAndGoContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            return View(await _context.Order.ToListAsync());
        }
      

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .SingleOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ZipCode,PostalAddress,PaymentCard,Cvv")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order.SingleOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ZipCode,PostalAddress,PaymentCard,Cvv")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .SingleOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Order.SingleOrDefaultAsync(m => m.Id == id);
            _context.Order.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Order.Any(e => e.Id == id);
        }
    }
}

DrinkAndGo/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DrinkAndGo.Models;
using Microsoft.AspNetCore.Http;

namespace DrinkAndGo.Controllers
{
    public class UsersController : Controller
    {
        private readonly DrinkAndGoContext _context;
        public static string UserRole = null;
        public static string UserName = null;

        public UsersController(DrinkAndGoContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            

            return View(await _context.User.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .SingleOrDefaultAsync(m => m.UserName == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }
        public async Task<IActionResult> Check()
        {
            var q = from u in _context.User.Distinct()
                    orderby u.Age
                    select u.Age;
            ViewBag.data = "[" + string.Join(",", q.ToList()) + "]";
            return View(await _context.User.ToListAsync());
        }
        public async Task<IActionResult> Search(string name, decimal age, string type)
        {
            var result = from d in _context.User
                         where (d.UserName == name && d.Age == age && d.Role == type)
                         select d;
            return View(await result.ToListAsync());
        }
        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserName,Age,Password,Role")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                UserRole = user.Role;
                UserName = user.UserName;
                await _context.SaveChangesAsync();
                HttpContext.Session.SetString("UserName", user.UserName);
                HttpContext.Session.SetString("UserRole", user.Role);
                return RedirectToAction("ThePreferredDrinks", "Drinks");
            }
            return View(user);
        }
        public IActionResult Login()
        {
            ViewBag.Fail = false;
            return View();
        }
        public IActionResult Logout()
        {
            HttpContext.Session.SetString("UserName", "");
            HttpContext.Session.SetString("UserRole", "");
            return RedirectToAction("ThePreferredDrinks", "Drinks");
           
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login([Bind("UserName,Password")] User user)
        {
            var result = from u in _context.User
                         where u.UserName == user.UserName && u.Password == user.Password
                         select u;

            if (result.ToList().Count > 0)
            {
               
                UserRole = result.FirstOrDefault().Role;
                UserName = result.FirstOrDefault().UserName;
                HttpContext.Session.SetString("UserName", UserName);
                HttpContext.Session.SetString("UserRole", UserRole);
                return RedirectToAction("ThePreferredDrinks", "Drinks");
            }

            ViewBag.Fail = true;



            return View(user);
        }
        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.SingleOrDefaultAsync(m => m.UserName == id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("UserName,Age,Password")] User user)
        {
            if (id != user.UserName)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserName))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .SingleOrDefaultAsync(m => m.UserName == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _context.User.SingleOrDefaultAsync(m => m.UserName == id);
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> AddToCart(int drinkId)
        {
            if (UserName == null)
                return View("Error", new ErrorViewModel() { Message = "User not connected, cant view cart" });

            var user = await _context.User.SingleOrDefaultAsync(m => m.UserName == UserName);

            if (user == null)
                return View("Error", new ErrorViewModel() { Message = "User not found, cant view cart" });

            var drink = await _context.Drink.SingleOrDefaultAsync(m => m.DrinkId == drinkId);

            if (drink == null)
                return View("Error", new ErrorViewModel() { Message = "Drink not found" });

            var cart = user.Cart;

            if (_context.Cart_Drinks.Count(c => c.DrinkId == drink.DrinkId && c.UserId == user.Id) == 0)
                cart.Add(new Cart_Drink() { DrinkId = drink.DrinkId, Drink = drink, UserId = user.Id, User = user, DrinkCount = 1 });
            else
            {
                var drinkChosen = _context.Cart_Drinks.FirstOrDefault(c => c.DrinkId == drink.DrinkId && c.UserId == user.Id);
                drinkChosen.DrinkCount++;
                //cart.Add(new Cart_Drink() { DrinkId = drink.DrinkId, Drink = drink, UserId = user.Id, User = user });
            }

            _context.SaveChanges();

            return Redirect(ControllerContext.HttpContext.Request.Headers["Referer"]); // redirect to last page
        }

        public async Task<IActionResult> ViewCart()
        {
            if (UserName == null)
                return View("Error", new ErrorViewModel() { Message = "User not connected, cant view cart" });

            var user = await _context.User.SingleOrDefaultAsync(m => m.UserName == UserName);

            if (user == null)
                return View("Error", new ErrorViewModel() { Message = "User not found, cant view cart" });


            Dictionary<int, int> drinkToCount = new Dictionary<int, int>();


            var drinks = _context.Cart_Drinks.Where(cd => cd.UserId == user.Id);

            foreach (var cart_Drink in drinks)
                drinkToCount[cart_Drink.DrinkId] = cart_Drink.DrinkCount;
            //if (drinkToCount.ContainsKey(cart_Drink.DrinkId))
            //    drinkToCount[cart_Drink.DrinkId] = drinkToCount[cart_Drink.DrinkId] + 1;
            //else
            //    drinkToCount[cart_Drink.DrinkId] = 1;

            Dictionary<Drink, int> result = new Dictionary<Drink, int>();
            foreach (var itm in drinkToCount)
                result[_context.Drink.FirstOrDefault(m => m.DrinkId == itm.Key)] = itm.Value;


            return View(result);
        }

        public async Task<IActionResult> RemoveFromCart(int drinkId)
        {
            if (UserName == null)
                return View("Error", new ErrorViewModel() { Message = "User not connected, cant view cart" });

            var user = await _context.User.SingleOrDefaultAsync(m => m.UserName == UserName);

            if (user == null)
                return View("Error", new ErrorViewModel() { Message = "User not found, cant view cart" });

            var drink = await _context.Drink.SingleOrDefaultAsync(m => m.DrinkId == drinkId);

            if (drink == null)
                return View("Error", new ErrorViewModel() { Message = "Drink not found" });

            var drinkChosen = _context.Cart_Drinks.FirstOrDefault(c => c.DrinkId == drink.DrinkId && c.UserId == user.Id);
            drinkChosen.DrinkCount--;

            if (drinkChosen.DrinkCount == 0)

DrinkAndGo/Views/Users/Check.cshtml
@model IEnumerable<DrinkAndGo.Models.User>

@{
    ViewData["Title"] = "Index";
}


@{
    ViewData["Title"] = "Index";
}
<br />
<br />
<br />
<br />
<p2>The following graph shows us the age of the users:</p2>
<br />
<br />
<br />
<script>
    var data = @ViewBag.data;
</script>


<br />
<br />
<br />


<div class="chart"></div>

<br />
<br />
<br />
<br />

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table" style="display:none">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Password)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.UserName">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.UserName">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.UserName">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

DrinkAndGo/Views/Users/Create.cshtml
@model DrinkAndGo.Models.User

@{
    ViewData["Title"] = "Create";
}
<br />
<br />
<br />
<h2>Register</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <input asp-for="Role" class="form-control" />
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>

            <img src="~/images/ajax-loader.gif" class="hide loader" />
            <button class="btn-danger btn btn-loader">Register</button>


         
            <br />
            <canvas id="myCanvas" width="200" height="100" style="border:1px solid #d3d3d3;"></canvas>
            <script>
                var c = document.getElementById("myCanvas");
                var ctx = c.getContext("2d");
                ctx.font = "30px Arial";
                ctx.fillText("WELCOME", 10, 50);
            </script>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DrinkAndGo/Views/Users/Delete.cshtml
@model DrinkAndGo.Models.User

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="UserName" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DrinkAndGo/Views/Users/Details.cshtml
@model DrinkAndGo.Models.User

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.UserName">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DrinkAndGo/Views/Users/Edit.cshtml
@model DrinkAndGo.Models.User

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UserName" />
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DrinkAndGo/Views/Users/Index.cshtml
@model IEnumerable<DrinkAndGo.Models.User>

@{
    ViewData["Title"] = "Index";
}
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "Index";
}
<br />
<br />
<br />
<br />

<form class="form-inline" asp-controller="Users" asp-action="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    <input class="form-control mr-sm-2" type="search" placeholder="Enter user name" aria-label="Search" name="name">
    <input class="form-control mr-sm-2" type="search" placeholder="Enter user age" aria-label="Search" name="age">
    <input class="form-control mr-sm-2" type="search" placeholder="Enter user type" aria-label="Search" name="type">
</form>



<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Password)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.UserName">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.UserName">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.UserName">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

DrinkAndGo/Views/Users/Login.cshtml
@model DrinkAndGo.Models.User

@{
    ViewData["Title"] = "Create";
}
<head>
    <script type="text/javascript" src="http://ajax.microsoft.com/ajax/jquery/jquery-1.3.2.min.js"></script>
</head>

<br />
<br />
<h2>Login</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>


            @if (ViewBag.Fail)
            {
                <div>Login failed. Please try again.</div>
            }
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DrinkAndGo/Views/Users/Search.cshtml
@model IEnumerable<DrinkAndGo.Models.User>

@{
    ViewData["Title"] = "Index";
}
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "Index";
}



<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Password)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.UserName">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.UserName">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.UserName">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

DrinkAndGo/Views/Users/ViewCart.cshtml
@using DrinkAndGo.Models
@model Dictionary<Drink, int>

@{
    ViewData["Title"] = "ViewCart";
}
<br />
<br />
<h2>Shopping Cart</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>

            <th>
                Price
            </th>
            <th>
                Image
            </th>

            <th>
                Count
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Key.Name)
                </td>


                <td>
                    @Html.DisplayFor(modelItem => item.Key.Price)
                </td>
                <td>
                    <img src="@Html.DisplayFor(modelItem => item.Key.ImageUrl)" alt="ASP.NET" class="img1" />
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Value)
                </td>
                <td>
                    <a asp-action="RemoveFromCart" asp-route-drinkId="@item.Key.DrinkId">Remove one</a>
                    <br />
                    <a asp-action="AddToCart" asp-route-drinkId="@item.Key.DrinkId">Add one</a>
                </td>
            </tr>
        }


    </tbody>

</table>
<div>
    <a class="btn btn-default" asp-controller="Orders" asp-action="Create">
        CHECHOUT
    </a>
</div>