DrinkAndGo/Controllers/StoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DrinkAndGo.Models;

namespace DrinkAndGo.Controllers
{
    public class StoresController : Controller
    {
        private readonly DrinkAndGoContext _context;

        public StoresController(DrinkAndGoContext context)
        {
            _context = context;
        }

        // GET: Stores
        public async Task<IActionResult> Index()
        {
            return View(await _context.Store.ToListAsync());
        }

        // GET: Stores/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var store = await _context.Store
                .SingleOrDefaultAsync(m => m.Name == id);
            if (store == null)
            {
                return NotFound();
            }

            return View(store);
        }

        // GET: Stores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Stores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,RealAdress,Adress")] Store store)
        {
            if (ModelState.IsValid)
            {
                _context.Add(store);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(store);
        }

        // GET: Stores/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var store = await _context.Store.SingleOrDefaultAsync(m => m.Name == id);
            if (store == null)
            {
                return NotFound();
            }
            return View(store);
        }

        // POST: Stores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Name,RealAdress,Adress")] Store store)
        {
            if (id != store.Name)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(store);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StoreExists(store.Name))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(store);
        }

        // GET: Stores/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var store = await _context.Store
                .SingleOrDefaultAsync(m => m.Name == id);
            if (store == null)
            {
                return NotFound();
            }

            return View(store);
        }

        // POST: Stores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var store = await _context.Store.SingleOrDefaultAsync(m => m.Name == id);
            _context.Store.Remove(store);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StoreExists(string id)
        {
            return _context.Store.Any(e => e.Name == id);
        }
    }
}

DrinkAndGo/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DrinkAndGo.Models;
using Microsoft.AspNetCore.Http;

namespace DrinkAndGo.Controllers
{
    public class UsersController : Controller
    {
        private readonly DrinkAndGoContext _context;
        public static string UserRole = null;
        public static string UserName = null;

        public UsersController(DrinkAndGoContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            

            return View(await _context.User.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .SingleOrDefaultAsync(m => m.UserName == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }
        public async Task<IActionResult> Check()
        {
            var q = from u in _context.User.Distinct()
                    orderby u.Age
                    select u.Age;
            ViewBag.data = "[" + string.Join(",", q.ToList()) + "]";
            return View(await _context.User.ToListAsync());
        }
        public async Task<IActionResult> Search(string name, decimal age, string type)
        {
            var result = from d in _context.User
                         where (d.UserName == name && d.Age == age && d.Role == type)
                         select d;
            return View(await result.ToListAsync());
        }
        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserName,Age,Password,Role")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                UserRole = user.Role;
                UserName = user.UserName;
                await _context.SaveChangesAsync();
                HttpContext.Session.SetString("UserName", user.UserName);
                HttpContext.Session.SetString("UserRole", user.Role);
                return RedirectToAction("ThePreferredDrinks", "Drinks");
            }
            return View(user);
        }
        public IActionResult Login()
        {
            ViewBag.Fail = false;
            return View();
        }
        public IActionResult Logout()
        {
            HttpContext.Session.SetString("UserName", "");
            HttpContext.Session.SetString("UserRole", "");
            return RedirectToAction("ThePreferredDrinks", "Drinks");
           
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login([Bind("UserName,Password")] User user)
        {
            var result = from u in _context.User
                         where u.UserName == user.UserName && u.Password == user.Password
                         select u;

            if (result.ToList().Count > 0)
            {
               
                UserRole = result.FirstOrDefault().Role;
                UserName = result.FirstOrDefault().UserName;
                HttpContext.Session.SetString("UserName", UserName);
                HttpContext.Session.SetString("UserRole", UserRole);
                return RedirectToAction("ThePreferredDrinks", "Drinks");
            }

            ViewBag.Fail = true;



            return View(user);
        }
        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.SingleOrDefaultAsync(m => m.UserName == id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("UserName,Age,Password")] User user)
        {
            if (id != user.UserName)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserName))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .SingleOrDefaultAsync(m => m.UserName == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _context.User.SingleOrDefaultAsync(m => m.UserName == id);
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> AddToCart(int drinkId)
        {
            if (UserName == null)
                return View("Error", new ErrorViewModel() { Message = "User not connected, cant view cart" });

            var user = await _context.User.SingleOrDefaultAsync(m => m.UserName == UserName);

            if (user == null)
                return View("Error", new ErrorViewModel() { Message = "User not found, cant view cart" });

            var drink = await _context.Drink.SingleOrDefaultAsync(m => m.DrinkId == drinkId);

            if (drink == null)
                return View("Error", new ErrorViewModel() { Message = "Drink not found" });

            var cart = user.Cart;

            if (_context.Cart_Drinks.Count(c => c.DrinkId == drink.DrinkId && c.UserId == user.Id) == 0)
                cart.Add(new Cart_Drink() { DrinkId = drink.DrinkId, Drink = drink, UserId = user.Id, User = user, DrinkCount = 1 });
            else
            {
                var drinkChosen = _context.Cart_Drinks.FirstOrDefault(c => c.DrinkId == drink.DrinkId && c.UserId == user.Id);
                drinkChosen.DrinkCount++;
                //cart.Add(new Cart_Drink() { DrinkId = drink.DrinkId, Drink = drink, UserId = user.Id, User = user });
            }

            _context.SaveChanges();

            return Redirect(ControllerContext.HttpContext.Request.Headers["Referer"]); // redirect to last page
        }

        public async Task<IActionResult> ViewCart()
        {
            if (UserName == null)
                return View("Error", new ErrorViewModel() { Message = "User not connected, cant view cart" });

            var user = await _context.User.SingleOrDefaultAsync(m => m.UserName == UserName);

            if (user == null)
                return View("Error", new ErrorViewModel() { Message = "User not found, cant view cart" });


            Dictionary<int, int> drinkToCount = new Dictionary<int, int>();


            var drinks = _context.Cart_Drinks.Where(cd => cd.UserId == user.Id);

            foreach (var cart_Drink in drinks)
                drinkToCount[cart_Drink.DrinkId] = cart_Drink.DrinkCount;
            //if (drinkToCount.ContainsKey(cart_Drink.DrinkId))
            //    drinkToCount[cart_Drink.DrinkId] = drinkToCount[cart_Drink.DrinkId] + 1;
            //else
            //    drinkToCount[cart_Drink.DrinkId] = 1;

            Dictionary<Drink, int> result = new Dictionary<Drink, int>();
            foreach (var itm in drinkToCount)
                result[_context.Drink.FirstOrDefault(m => m.DrinkId == itm.Key)] = itm.Value;


            return View(result);
        }

        public async Task<IActionResult> RemoveFromCart(int drinkId)
        {
            if (UserName == null)
                return View("Error", new ErrorViewModel() { Message = "User not connected, cant view cart" });

            var user = await _context.User.SingleOrDefaultAsync(m => m.UserName == UserName);

            if (user == null)
                return View("Error", new ErrorViewModel() { Message = "User not found, cant view cart" });

            var drink = await _context.Drink.SingleOrDefaultAsync(m => m.DrinkId == drinkId);

            if (drink == null)
                return View("Error", new ErrorViewModel() { Message = "Drink not found" });

            var drinkChosen = _context.Cart_Drinks.FirstOrDefault(c => c.DrinkId == drink.DrinkId && c.UserId == user.Id);
            drinkChosen.DrinkCount--;

            if (drinkChosen.DrinkCount == 0)

DrinkAndGo/Views/Shared/_Layout.cshtml
@using DrinkAndGo.Controllers
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Drink&Go</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Drink&Go</a>
            </div>
            <form class="form-inline" asp-controller="Drinks" asp-action="Search">
                <img src="~/images/ajax-loader.gif" class="hide loader" />
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                <input class="form-control mr-sm-2" type="search" placeholder="Instock/Not instock" aria-label="Search" name="instok">
                <input class="form-control mr-sm-2" type="search" placeholder="Enter max price" aria-label="Search" name="price">
                <input class="form-control mr-sm-2" type="search" placeholder="Enter drink name" aria-label="Search" name="drinkname">           
                @if (Context.Session.GetString("UserName") != "" && Context.Session.GetString("UserName") != null)
                {
                <div>Hello @Context.Session.GetString("UserName")</div>
                }
            </form>

                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @if (@Context.Session.GetString("UserRole") == "Admin")
                        {
                            <li><a asp-area="" asp-controller="Drinks" asp-action="Index">All Drinks</a></li>
                            <li><a asp-area="" asp-controller="Drinks" asp-action="Alcoholic">Alcoholic</a></li>
                            <li><a asp-area="" asp-controller="Drinks" asp-action="NonAlcoholic">Non Alcholic</a></li>
                            <li><a asp-area="" asp-controller="Stores" asp-action="Index">Contact And Stores</a></li>
                            @if (Context.Session.GetString("UserName") == "" || Context.Session.GetString("UserName") == null)
                            {
                                <li><a asp-area="" asp-controller="Users" asp-action="Login">Login</a></li>
                            }
                            else
                            {
                                <li><a asp-area="" asp-controller="Users" asp-action="Logout">Logout</a></li>
                            }

                            <li><a asp-area="" asp-controller="Users" asp-action="Index">All Users</a></li>
                        }
                        @if (@Context.Session.GetString("UserRole") == "Official")
                        {
                            <li><a asp-area="" asp-controller="Drinks" asp-action="Index">All Drinks</a></li>
                            <li><a asp-area="" asp-controller="Drinks" asp-action="Alcoholic">Alcoholic</a></li>
                            <li><a asp-area="" asp-controller="Drinks" asp-action="NonAlcoholic">Non Alcholic</a></li>
                            <li><a asp-area="" asp-controller="Stores" asp-action="Index">Contact And Stores</a></li>
                            <li><a asp-area="" asp-controller="Users" asp-action="Logout">Logout</a></li>
                            <li><a asp-area="" asp-controller="Users" asp-action="ViewCart">My Cart 🛒</a> </li>

                        }
                        @if (@Context.Session.GetString("UserRole") != "Admin" && @Context.Session.GetString("UserRole") != "Official")
                        {
                            <li><a asp-area="" asp-controller="Drinks" asp-action="Index">All Drinks</a></li>
                            <li><a asp-area="" asp-controller="Drinks" asp-action="Alcoholic">Alcoholic</a></li>
                            <li><a asp-area="" asp-controller="Drinks" asp-action="NonAlcoholic">Non Alcholic</a></li>
                            <li><a asp-area="" asp-controller="Stores" asp-action="Index">Contact And Stores</a></li>
                            @if (Context.Session.GetString("UserName") == null || Context.Session.GetString("UserName") == "")
                            {
                                <li><a asp-area="" asp-controller="Users" asp-action="Login">Login</a></li>
                            }
                            else
                            {
                                <li><a asp-area="" asp-controller="Users" asp-action="Logout">Logout</a></li>
                            }
                            <li><a asp-area="" asp-controller="Users" asp-action="Create">Register</a></li>
                        }
                    </ul>

                </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Drink&Go</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">arch
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
    <script src="https://d3js.org/d3.v3.min.js" charset="utf-8"></script>
</body>
</html>